# Generated by Django 6.0.6 on 2026-06-17 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ejercicio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/', verbose_name='Imagen del Ejercicio')),
                ('descripcion_ejercicio', models.TextField(blank=True, verbose_name='Descripción del Ejercicio')),
                ('autorizado', models.BooleanField(default=False, verbose_name='¿Autorizado para mostrar en la app?')),
                ('tipo_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_types.tipoejercicio')),
            ],
        ),
    ]
