# Generated by Django 6.0.6 on 2026-06-19 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_types', '0001_initial'),
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Autor/Entrenador'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/ejercicios/', verbose_name='Imagen del Ejercicio'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre_ejercicio',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ejercicio*'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo_ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_types.tipoejercicio', verbose_name='Tipo de Ejercicio*'),
        ),
    ]
