# Generated by Django 6.0.6 on 2026-07-10 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_types', '0002_tipoejercicio_activo'),
        ('exercises', '0002_ejercicio_autor_alter_ejercicio_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Ejercicio Activo?'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Autor/Entrenador'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo_ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercise_types.tipoejercicio', verbose_name='Tipo de Ejercicio*'),
        ),
    ]
