# Generated by Django 6.0.6 on 2026-06-20 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_ejercicio_autor_alter_ejercicio_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rutina', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Rutina*')),
                ('descripcion_rutina', models.TextField(blank=True, verbose_name='Descripción de la Rutina')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Autor/Entrenador')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
            },
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(default=3, verbose_name='Número de Series')),
                ('descanso', models.IntegerField(default=20, verbose_name='Descanso entre series (segundos)')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden del Ejercicio en la Rutina')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ejercicio', verbose_name='Ejercicio incluido en la rutina')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_plans.rutina')),
            ],
            options={
                'verbose_name': 'Ejercicio de la Rutina',
                'verbose_name_plural': 'Ejercicios de la Rutina',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(related_name='rutinas_incluidas', through='exercise_plans.RutinaEjercicio', to='exercises.ejercicio', verbose_name='Ejercicios incluidos en la rutina*'),
        ),
    ]
