# Generated by Django 6.0.6 on 2026-06-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutinaejercicio',
            options={'verbose_name': 'Ejercicio de la Rutina', 'verbose_name_plural': 'Ejercicios de la Rutina'},
        ),
        migrations.RemoveField(
            model_name='rutinaejercicio',
            name='orden',
        ),
    ]
