# Generated by Django 6.0.6 on 2026-06-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_plans', '0002_alter_rutinaejercicio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='publico',
            field=models.BooleanField(default=False, verbose_name='¿Es pública?'),
        ),
    ]
