# Generated by Django 6.0.6 on 2026-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_plans', '0003_rutina_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='nombre_rutina',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Rutina*'),
        ),
    ]
