# Generated by Django 6.0.6 on 2026-07-03 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_plans', '0004_alter_rutina_nombre_rutina'),
        ('exercises', '0002_ejercicio_autor_alter_ejercicio_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='domingo',
            field=models.BooleanField(default=False, verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='jueves',
            field=models.BooleanField(default=False, verbose_name='Jueves'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='lunes',
            field=models.BooleanField(default=False, verbose_name='Lunes'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='martes',
            field=models.BooleanField(default=False, verbose_name='Martes'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='miercoles',
            field=models.BooleanField(default=False, verbose_name='Miércoles'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='sabado',
            field=models.BooleanField(default=False, verbose_name='Sábado'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='viernes',
            field=models.BooleanField(default=False, verbose_name='Viernes'),
        ),
        migrations.AddConstraint(
            model_name='rutina',
            constraint=models.UniqueConstraint(fields=('autor', 'nombre_rutina'), name='unique_rutina_per_user'),
        ),
    ]
