# Generated by Django 6.0.6 on 2026-07-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_plans', '0005_rutina_domingo_rutina_jueves_rutina_lunes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='hora_correo',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del correo'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='hora_popup',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora del Pop-up'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='recordatorio_correo',
            field=models.BooleanField(default=False, verbose_name='Enviar recordatorio por correo'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='recordatorio_popup',
            field=models.BooleanField(default=False, verbose_name='Mostrar Pop-up en Inicio'),
        ),
    ]
