# Generated by Django 6.0.6 on 2026-07-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_plans', '0006_rutina_hora_correo_rutina_hora_popup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
