# Generated by Django 6.0.6 on 2026-07-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_plans', '0008_alter_rutina_autor'),
        ('exercises', '0003_ejercicio_activo_alter_ejercicio_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.ejercicio', verbose_name='Ejercicio incluido en la rutina'),
        ),
    ]
