# Generated by Django 6.0.6 on 2026-07-10 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_plans', '0009_alter_rutinaejercicio_ejercicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='es_snapshot',
            field=models.BooleanField(default=False, verbose_name='¿Es una copia congelada para el foro?'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='rutina_padre',
            field=models.ForeignKey(blank=True, help_text='Apunta a la rutina original viva creada por el entrenador.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='exercise_plans.rutina'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('enlace', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
