# Generated by Django 6.0.6 on 2026-06-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, unique=True, verbose_name='Grupo Muscular')),
            ],
            options={
                'verbose_name': 'Tipo de Ejercicio',
                'verbose_name_plural': 'Tipos de Ejercicios',
            },
        ),
    ]
