# Generated by Django 6.0.6 on 2026-07-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoejercicio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
    ]
