# Generated by Django 6.0.6 on 2026-06-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100, unique=True, verbose_name='Grupo Muscular')),
            ],
            options={
                'verbose_name': 'Tipo de Ejercicio',
                'verbose_name_plural': 'Tipos de Ejercicios',
            },
        ),
    ]
