# Generated by Django 6.0.6 on 2026-06-08 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipoejercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ejercicio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/', verbose_name='Imagen del Ejercicio')),
                ('tipo_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoejercicio')),
            ],
        ),
    ]
