# Generated by Django 6.0.6 on 2026-06-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion_ejercicio',
            field=models.TextField(blank=True, verbose_name='Descripción del Ejercicio'),
        ),
    ]
