# Generated by Django 6.0.6 on 2026-07-05 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sesionentrenamiento'),
        ('exercise_plans', '0006_rutina_hora_correo_rutina_hora_popup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.PositiveIntegerField(verbose_name='Número de Serie')),
                ('peso_levantado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exercise_plans.rutinaejercicio')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.sesionentrenamiento')),
            ],
        ),
    ]
