# Generated by Django 6.0.6 on 2026-06-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ejercicio_descripcion_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='autorizado',
            field=models.BooleanField(default=False, verbose_name='¿Autorizado para mostrar en la app?'),
        ),
    ]
