# Generated by Django 6.0.6 on 2026-07-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registroserie'),
        ('exercise_plans', '0008_alter_rutina_autor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registroserie',
            constraint=models.UniqueConstraint(fields=('sesion', 'bloque', 'numero_serie'), name='unique_serie_por_bloque_y_sesion'),
        ),
    ]
