# Generated by Django 6.0.6 on 2026-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registroserie_unique_serie_por_bloque_y_sesion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminoscondiciones',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Términos y Condiciones', 'verbose_name_plural': 'Historial de Términos y Condiciones'},
        ),
        migrations.AddField(
            model_name='terminoscondiciones',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='¿Es la versión vigente?'),
        ),
        migrations.AddField(
            model_name='terminoscondiciones',
            name='titulo',
            field=models.CharField(default='Términos y Condiciones Generales', help_text='Ej: TyC Actualización Ley de Protección 2026', max_length=150, verbose_name='Título de la Versión'),
        ),
        migrations.AlterField(
            model_name='terminoscondiciones',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicación'),
        ),
    ]
