# Generated by Django 6.0.6 on 2026-06-23 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(help_text='Asi se llamará la publicación')),
                ('texto', models.TextField(help_text='Escribe tu consejo o mensaje aquí')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='foro_imagenes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
                ('rutina_vinculada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise_plans.rutina')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
